/* ---------------------------------------------------------------------------
 * pdfTranslator/configWriter.ts  –  Generate config files for pdf2zh_next
 *
 * Produces two files consumed by aidea_bridge.py:
 *   1. config.toml  — pdf2zh_next translation engine configuration
 *   2. task.json    — bridge script parameters
 * -------------------------------------------------------------------------*/

import type { BridgeTask } from "./types";

/**
 * Generate a config.toml string for pdf2zh_next with openaicompatible service.
 *
 * Only the openaicompatible service is enabled; all others are disabled.
 * The OAuth access_token is passed as openai_compatible_api_key.
 */
export function generateConfigToml(params: {
  model: string;
  apiKey: string;
  apiUrl: string;
  sourceLang: string;
  targetLang: string;
  qps: number;
  noDual: boolean;
  noMono: boolean;
}): string {
  // TOML doesn't have a standard JS library in Zotero/Gecko,
  // so we build the string manually.  This is safe because all
  // values are either numbers, booleans, or controlled strings.
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

  return `# Auto-generated by AIdea plugin — do not edit
openaicompatible = true

[translation]
lang_in = "${esc(params.sourceLang)}"
lang_out = "${esc(params.targetLang)}"
qps = ${params.qps}
ignore_cache = false

[pdf]
no_dual = ${params.noDual}
no_mono = ${params.noMono}
watermark_output_mode = "no_watermark"
use_alternating_pages_dual = true

[openaicompatible_detail]
translate_engine_type = "OpenAICompatible"
support_llm = "yes"
openai_compatible_model = "${esc(params.model)}"
openai_compatible_base_url = "${esc(params.apiUrl)}"
openai_compatible_api_key = "${esc(params.apiKey)}"
openai_compatible_timeout = "120"
`;
}

/**
 * Generate the task.json string for aidea_bridge.py.
 */
export function generateTaskJson(task: BridgeTask): string {
  return JSON.stringify(task, null, 2);
}
