// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiBase": string;
      "apiKey": string;
      "model": string;
      "primaryConnectionMode": string;
      "apiBasePrimary": string;
      "apiKeyPrimary": string;
      "modelPrimary": string;
      "apiBaseSecondary": string;
      "apiKeySecondary": string;
      "modelSecondary": string;
      "apiBaseTertiary": string;
      "apiKeyTertiary": string;
      "modelTertiary": string;
      "apiBaseQuaternary": string;
      "apiKeyQuaternary": string;
      "modelQuaternary": string;
      "systemPrompt": string;
      "oauthModelListCache": string;
      "oauthModelSelectionCache": string;
      "oauthSetupLog": string;
      "showPopupAddText": boolean;
      "temperaturePrimary": string;
      "maxTokensPrimary": string;
      "temperatureSecondary": string;
      "maxTokensSecondary": string;
      "temperatureTertiary": string;
      "maxTokensTertiary": string;
      "temperatureQuaternary": string;
      "maxTokensQuaternary": string;
      "shortcuts": string;
      "shortcutLabels": string;
      "shortcutDeleted": string;
      "customShortcuts": string;
      "shortcutOrder": string;
      "showAllModels": boolean;
    };
  }
}
